"use client";
import { useState } from "react";
import Link from "next/link";
export default function ForgotPage() {
  const [email, setEmail] = useState(""); const [token, setToken] = useState(() => typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("token") ?? ""); const [password, setPassword] = useState(""); const [message, setMessage] = useState("");
  async function request(e: React.FormEvent) { e.preventDefault(); const r = await fetch("/api/auth/password-reset", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); const d = await r.json(); setToken(d.devToken ?? ""); setMessage("If an account exists, reset instructions have been prepared."); }
  async function reset(e: React.FormEvent) { e.preventDefault(); const r = await fetch("/api/auth/password-reset", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, password }) }); const d = await r.json(); setMessage(r.ok ? "Password updated. You can now sign in." : d.error); }
  return <main className="mx-auto max-w-md px-5 py-16"><h1 className="text-3xl font-extrabold">Reset password</h1><p className="mt-2 text-sm text-muted">Reset links expire after 30 minutes and can only be used once.</p><form onSubmit={request} className="mt-6 space-y-3"><input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@university.edu" className="h-11 w-full rounded-xl border border-line px-3" /><button className="button primary" type="submit">Request reset</button></form>{token && <form onSubmit={reset} className="mt-6 space-y-3"><input required value={token} onChange={e => setToken(e.target.value)} className="h-11 w-full rounded-xl border border-line px-3 text-xs" /><input required minLength={8} type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="New password" className="h-11 w-full rounded-xl border border-line px-3" /><button className="button" type="submit">Set new password</button></form>}{message && <p role="status" className="mt-4 text-sm">{message}</p>}<Link href="/login" className="mt-6 block text-sm underline">Back to sign in</Link></main>;
}
